name: fullcycle-docker-nginx-node-challenge

services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - node-network
    depends_on:
      - db
      - node

  node:
    container_name: node
    restart: always
    tty: true
    build:
      context: ./node
      dockerfile: Dockerfile
    volumes:
      - ./node:/usr/src/node
      - /usr/src/node/node_modules
    networks:
      - node-network
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:9.1
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fullcycle
    networks:
      - node-network
    ports:
      - "3306:3306"


networks:
  node-network:
    driver: bridge